### PR TITLE
Tabular data view added, see https://github.com/tyrasd/overpass-ide/issues/8

### PR DESCRIPTION
**Pull request by jongleur1983**
Not beautiful yet - detailed css is missing, and with lot's of ideas to extend further, but working, and basically solving the issue #8.

As a side node I changed the view buttons (Map, Data) functionality to easily support more than two tabs
(I added a third one for the table), and slightly generalized the css code.

### CODE REVIEW

**Comment by mmd-osm** [comment]
Demo only works with http at this time: http://jongleur1983.github.io/overpass-ide/

sc3

**Comment by bjohas** [comment]
This is great - thanks. It would be amazing is if there were links added, e.g. as three small icons at the start of each row, to:
Osm (view)
Osm (edit)
Josm remote control.

This would allow editing the data as needed. Similar to the normal map output that has link to osm, and also similar to what osmose does.

**Comment by bjohas** [comment]
It seems the 'table' view does not show relations - would be great if it did!

**Comment by bjohas** [comment]
Some more thoughts:

I'd say it was important to:
- show relations
- have more than 100 entries - there should be an "all" option.

Nice to have:
- It could be nice be great if you could control the order of certain fields, to put whatever fields deemed important first. This could use the [csv:("name","ref")] syntax.
- It would also be great if there was a 'download' button at the bottom, that downloaded the raw data. 

Overall, this looks really great though! Thanks for working on this!

**Comment by mmd-osm** [comment]
@bjohas : before getting too excited over the demo, please keep in mind that this pull request is almost 3 years old. I guess those involved might have other priorities right now (maybe I'm wrong here).

There's some great opportunity to get this prototype ready for inclusion. If you're interested, you should probably sync up with @tyrasd.

**Comment by jongleur1983** [comment]
Hi.
I started this pull request, but you're right, it's slightly out of my scope currently.
I'm happy about the interest and any possible progress it get's again now, but I have no idea if and when I'll have time to work on it again, especially as I didn't do much in Javascript in the last months.

So if anybody else want's to help, feel free to start.

**Comment by bjohas** [comment]
Thanks for the feedback!

Do you think it may be worth sending a message to the dev list, seeing whether anybody else is interested?

**Comment by jongleur1983** [comment]
no idea, not sure. I didn't even know there's a dev list for overpass turbo, I prefer following github issues directly usually, but why not?

**Comment by bjohas** [comment]
I've forked @jongleur1983 's version, and merged it with upstream, see https://github.com/bjohas/overpass-ide/commits/gh-pages. I need to do a fair bit more testing, but it seems to work so far.

**Comment by jongleur1983** [comment]
cool, thanks.

**Comment by d1g** [comment]
Based on what I seen in
> http://jongleur1983.github.io/overpass-ide/

* 1. "add column" and "remove column" controls can be moved below the table (i.e. inactive area)
* 1a. "remove column" controls can be removed afterwards
* 2. Show "10" entries control can be merged within "Showing 1 to 10 of 72 entries" text
* 3. next/previous page should be bigger
* 4. I want possibility to pageup/pagedown them using keyboard (or CTRL + left/right)
* 5. 25 lines should be default (not 10)
* 6. there should be visible link to "download csv" (in order to use more comprehensive CSV tools)
* 7. "Table" can be renamed to CSV, older tab "Data" to "OSM XML"

**Comment by saerdnaer** [comment]
> "Table" can be renamed to CSV, older tab "Data" to "OSM XML"
Data tab might also show OSM JSON, depending on the query.

**Comment by mmd-osm** [comment]
Hmm... what happened to this one? Stale, obsolete?

**Comment by bjohas** [comment]
I'm still very interested in this. Happy to help out in some way.

**Comment by d1g** [comment]
I think that the best read-only option is to export to csv

Then we would have many solutions e.g.: http://nicolas.kruchten.com/pivottable/examples/index.html

**Comment by bjohas** [comment]
A webservice would still be good, to allow linking directly from overpass-turbo. It could be built outside of overpass-turbo, as an independent service (though it would require a separate API query). However, for fast inspection, something sits within overpass-turbo (and allows queries to made, adjusted etc) could be helpful.

**Comment by tyrasd** [comment]
> Stale

Yeah. Since we already have a dedicated feature-request ticket for this, I think it makes sense continue  discussions there: #8

**Pull request closed without merging**
