### PR TITLE
Added warning if Overpass API result exceeds 24/96 hours

### PR DESCRIPTION
**Pull request by mmd-osm**
See issue #88 - adds a yellow background as shown on the screenshot

### CODE REVIEW

**Comment by tyrasd** [comment]
thanks!

**Comment by mmd-osm** [comment]
When do you plan to push this PR to gh-pages? Rambler instance is lagging behind again, and I was expecting to see that yellow background.

**Comment by tyrasd** [comment]
Oh, sorry. There are still some half-baked commits in master which I planned to finish before merging all into the stable branch. But, as that could take another couple of weeks ( :cry: ), I'll just cherry-pick this one into `gh-pages`. Is there anything else important for you just waiting to be deployed? Sorry again.

**Comment by mmd-osm** [comment]
NP, I also somehow lost a bit track of this patch... I guess there might be some patches for LearnOverpass out there, but I guess they're not that time critical...

Thanks a lot again!

**Pull request merged**
