### PR TITLE
Use ES6 modules, use module bundler

### PR DESCRIPTION
**Pull request by simon04**
- [x] install packages from npm via
- [x] use ES6 module `export`/`import`
- [x] use [webpack](https://webpack.js.org/) for bundling the application
- [ ] make the tests run again

This is work in progress; so far items 1+2 are started but not yet finished. What do you think?

### CODE REVIEW

**Comment by tyrasd** [comment]
:heart_eyes: 

> What do you think?

Definitively a +1 from me. Thanks for tackling this!

**Comment by simon04** [comment]
You can give it a try: `npm install && npm run start` for a development server and `npm run build` for a minified distribution build (see README for details).

I think we can drop the `_packaged.html` files completely. It's now just a matter of running webpack in a different mode.

I still have to look into building `map.html`. Eventually, we can get rid of quite a few files in the repo.

**Comment by tyrasd** [comment]
> I think we can drop the `_packaged.html` files completely. 

Yes. That's what I meant. ;-)

**Comment by tyrasd** [comment]
I've pushed this PR onto a new branch in this repo now and added you as a collaborator, so we can work on this together! I'm opening a new PR for that branch in a minute.

**Pull request closed without merging**
