### PR TITLE
Adding way + relation to initial example

### LINKED ISSUE #478: Search for camp_site fails
A known camp_site is not found ...
Using:
node 
  [tourism=camp_site]
  ({{bbox}});
out;

image

### PR DESCRIPTION
**Pull request by HolgerJeromin**
Closes #478 

Please test before merge. I am no overpass expert.

### CODE REVIEW

**Comment by mmd-osm** [comment]
You're not including nodes for the way, or ways/nodes for the relation here. A user will not see any of the ways/relations on the map.

**Comment by mmd-osm** [comment]
The new query doesn't include any way nodes or relation members...

**Comment by simon04** [comment]
Let's keep the initial example small and basic. For more advanced use-cases, please use the query wizard or other examples.

**Comment by HolgerJeromin** [comment]
The reason I expanded the example is that no one reads documentation or searches for other example if he **thinks** he knows enough.

A user opens the website, manipulates stuff and is disappointed. Even after @mmd-osm explained the problem the result in the head of the user was "osm is garbage". In this case even literally written.

**Comment by HolgerJeromin** [comment]
Perhaps it would be even better if there were no example at all. This way no one will learn wrong things.

**Pull request closed without merging**
